INSERT INTO
  UserData_t (
    `UserID`,
    `FirstName`,
    `LastName`,
    `ProfilePicture`,
    `ProfilePictureBorder`,
    `ProfilePictureBackground`,
    `Rating`,
    `LocationCity`,
    `LocationState`,
    `Facebook`,
    `Instagram`,
    `Twitter`,
    `LinkedIn`,
    `Mentoring`,
    `AboutMe`,
    `WorkTitle`,
    `WorkLocation`,
    `WorkStartDate`,
    `WorkEndDate`,
    `WorkDescription`,
    `EducationDegree`,
    `EducationLocation`,
    `EducationStartDate`,
    `EducationEndDate`,
    `EducationDescription`,
    `Associations`
  )
VALUES
  (
    1,
    'David',
    'Anderson',
    'david-anderson.png',
    '#008a0e',
    'biotech-pattern.png',
    4,
    'Boston',
    'Massachusetts',
    'david.anderson',
    'david.anderson',
    'david.anderson',
    'david.anderson',
    'David Anderson, an accomplished chemist with a passion for nurturing talent, is offering invaluable mentoring opportunities to aspiring chemists. Recognizing the importance of guidance and support in one\'s scientific journey, David is eager to share his knowledge and experiences with enthusiastic individuals looking to make their mark in the field. Through personalized mentoring sessions, he provides guidance on career paths, research methodologies, laboratory techniques, and scientific writing. David\'s patient and approachable nature fosters a supportive environment where mentees can gain practical insights, develop their skills, and embark on a successful career in chemistry with confidence.',
    'Introducing David, a talented and dedicated chemist with a profound passion for unraveling the mysteries of matter. With a strong educational background and years of hands-on experience in the field, he thrives in the laboratory, meticulously conducting experiments and analyzing chemical reactions. David\'s relentless pursuit of scientific discovery and his expertise in analytical techniques make him a valuable asset in advancing our understanding of the world at the molecular level.',
    'Research Chemist',
    'DEF Chemicals',
    '2018-03-23',
    null,
    'David actively contributes to the development of novel pharmaceutical compounds, conducting in-depth research, and performing experiments to assess their efficacy and safety. He collaborates with interdisciplinary teams to optimize formulations and improve manufacturing processes. David also plays a key role in analyzing data, preparing technical reports, and presenting findings to stakeholders.',
    'Ph.D. in Chemistry',
    'Massachussetts Institute of Technology',
    '2015-08-24',
    '2018-05-10',
    'David pursued his doctoral studies in Chemistry, specializing in a specific field such as organic chemistry, inorganic chemistry, or physical chemistry. He conducted in-depth research, published scientific papers, and presented his findings at conferences. His Ph.D. research focused on advancing knowledge in a specific area of chemistry, demonstrating his expertise and dedication to the field.',
    '2;3;4;5;6'
  ),
  (
    2,
    'Benjamin',
    'Park',
    'benjamin-park.png',
    '#800000',
    'biotech-pattern.png',
    5,
    'Los Angeles',
    'California',
    'benjamin.park',
    'benjamin.park',
    'benjamin.park',
    'benjamin.park',
    'Benjamin\'s passion for the legal profession extends beyond his practice as an attorney. He is also deeply committed to mentoring and sharing his expertise with aspiring lawyers and legal professionals. With his extensive experience in civil litigation, corporate law, and contract negotiations, Benjamin is well-equipped to offer guidance in these areas. His in-depth knowledge of legal research, negotiation strategies, and courtroom advocacy makes him a valuable resource for those seeking mentorship. Whether it\'s providing career advice, offering insights into legal practice, or assisting with specific legal challenges, Benjamin is always eager to lend a helping hand and inspire the next generation of legal minds.',
    'Meet Benjamin, a seasoned and knowledgeable lawyer with a passion for advocating justice and upholding the law. With sharp analytical skills and a persuasive demeanor, he excels in providing expert legal counsel and representation to clients. Benjamin\'s commitment to professionalism, integrity, and client-centered service has earned him a reputation for delivering successful outcomes and building strong relationships in the legal community.',
    'Attorney-at-Law',
    'Thompson & Mitchell Law Associates',
    '2010-09-01',
    null,
    'Benjamin has a proven track record of achieving favorable results for his clients in a wide range of legal matters. He conducts thorough research, prepares persuasive arguments, and navigates complex legal frameworks to build strong cases. Benjamin\'s expertise spans across civil litigation, corporate law, and contract negotiations. His strong negotiation skills and strategic approach contribute to successful settlements and favorable judgments on behalf of his clients.',
    'Juris Doctor (J.D.)',
    'Harvard Law School',
    '2007-08-30',
    '2010-05-27',
    'Benjamin earned his Juris Doctor degree from Harvard Law School, renowned for its rigorous legal education and distinguished faculty. He gained a solid foundation in legal theory, constitutional law, and legal research and writing. During his time at law school, Benjamin actively participated in moot court competitions and served on the editorial board of the law review, further honing his legal skills and cultivating a deep understanding of legal principles. His academic achievements and commitment to excellence laid the groundwork for a successful career in law.',
    '1;4;5;6'
  ),
  (
    3,
    'Harper',
    'Brown',
    'harper-brown.png',
    '#2565c7',
    'biotech-pattern.png',
    null,
    'Seattle',
    'Washington',
    'harper.brown',
    'harper.brown',
    'harper.brown',
    'harper.brown',
    null,
    'Meet Harper, a dedicated and innovative IT professional with a knack for problem-solving. With a deep passion for cutting-edge technologies and a keen eye for detail, she thrives in the dynamic world of IT. Her strong educational background in computer science, combined with her adaptability and creative thinking, enables her to develop impactful solutions that drive business growth.',
    'Data Scientist',
    'Data Analytics Corp.',
    '2019-03-15',
    null,
    'Harper excels in leveraging data to extract valuable insights and optimize business strategies. She collaborates with cross-functional teams to design and implement data-driven models, delivering accurate predictions and recommendations. Her expertise in programming languages such as R and Python allows her to build robust statistical models and conduct in-depth data analysis to drive informed decision-making.',
    'Master of Science in Data Science',
    'Stanford University',
    '2017-09-01',
    '2019-05-31',
    'Harper pursued her graduate studies in Data Science at Stanford University, where she honed her skills in advanced statistical analysis, machine learning, and data visualization. She actively participated in research projects and collaborated with industry partners to solve real-world data challenges. Her strong academic performance and dedication to continuous learning have equipped her with a solid foundation for applying cutting-edge techniques in data-driven decision-making.',
    '1;4;6'
  ),
  (
    4,
    'Lucas',
    'Khan',
    'lucas-khan.png',
    '#9900cc',
    'biotech-pattern.png',
    null,
    'Chicago',
    'Illinois',
    'lucas.khan',
    'lucas.khan',
    'lucas.khan',
    'lucas.khan',
    null,
    'Meet Lucas, a passionate and dedicated high school teacher committed to nurturing students\' intellectual growth and fostering a love for learning. With a warm and engaging teaching style, he creates a supportive classroom environment that encourages students to reach their full potential. Lucas\'s enthusiasm for his subject matter and her ability to connect with students make him an inspiring educator who is deeply invested in their academic and personal development.',
    'High English School Teacher',
    'Lincoln High School',
    '2012-08-20',
    null,
    'Lucas has made a significant impact on his students\' lives through his innovative teaching methods and personalized approach. He develops engaging lesson plans, incorporating multimedia resources and interactive activities to promote student engagement and understanding. Lucas also works closely with colleagues to collaborate on curriculum development and implement effective teaching strategies. His commitment to student success is evident in the improved academic performance and increased motivation of his students.',
    'Bachelor of Arts in English Education',
    'University of Illinois at Urbana-Champaign',
    '2008-08-25',
    '2012-05-12',
    'Lucas completed his undergraduate studies in English Education at the University of Illinois at Urbana-Champaign. He gained a comprehensive understanding of pedagogy, instructional strategies, and educational psychology. Through his coursework and field experiences, Lucas developed the necessary skills to create inclusive and student-centered learning environments. He actively participated in student teaching placements, working with diverse student populations and adapting his instruction to meet their individual needs. Lucas\'s dedication to his profession and his commitment to ongoing professional development contribute to his effectiveness as a high school English teacher.',
    '1;2;3;6'
  ),
  (
    5,
    'Mia',
    'Wilson',
    'mia-wilson.png',
    '#33cc33',
    'biotech-pattern.png',
    null,
    'New York City',
    'New York',
    'mia.wilson',
    'mia.wilson',
    'mia.wilson',
    'mia.wilson',
    null,
    'Meet Mia, a driven and results-oriented stock broker with a passion for financial markets and investment strategies. With a sharp analytical mind and a deep understanding of market trends, she excels in helping clients navigate the complexities of the stock market. Her exceptional communication skills and attention to detail enable her to provide personalized investment advice and deliver excellent service to her clients.',
    'Stock Broker',
    'Capital Investments LLC',
    '2015-06-10',
    null,
    'Mia has successfully guided numerous clients in making sound investment decisions to grow their portfolios. Shee conducts thorough research, analyzes market data, and identifies profitable investment opportunities. Her expertise in risk management and portfolio diversification has helped clients achieve their financial goals and build long-term wealth.',
    'Bachelor of Business Administration in Finance',
    'Wharton School of the University of Pennsylvania',
    '2011-09-05',
    '2015-05-17',
    'Mia completed her undergraduate studies in Finance at the prestigious Wharton School of the University of Pennsylvania. She gained a comprehensive understanding of financial markets, investment principles, and corporate finance. Through internships and extracurricular activities, she developed practical skills in analyzing financial statements, evaluating investment opportunities, and understanding market dynamics. Her academic excellence and involvement in finance-related clubs further enhanced her knowledge and passion for the field.',
    '1;2;6'
  ),
  (
    6,
    'Sophia',
    'Lee',
    'sophia-lee.png',
    '#fa7811',
    'circuits-pattern.png',
    null,
    'Washington',
    'District of Columbia',
    'sophia.lee',
    'sophia.lee',
    'sophia.lee',
    'sophia.lee',
    null,
    'Meet Sophia, a dynamic and talented IT professional with a passion for innovation and problem-solving. With a strong educational background in computer science and a natural curiosity for emerging technologies, she thrives in the fast-paced world of IT. Her dedication, adaptability, and keen eye for detail make her an invaluable asset in developing cutting-edge solutions that propel businesses forward.',
    'Software Engineeer',
    'Innovate Inc.',
    '2020-09-26',
    null,
    'Sophia plays a key role in developing and maintaining scalable software solutions for a diverse range of clients. She collaborates with cross-functional teams to design and implement efficient code, ensuring high-quality deliverables within strict deadlines. Her expertise in programming languages such as Java and Python helps to streamline processes and enhance system performance.',
    'Bachelor of Science in Computer Science',
    'The George Washington University',
    '2016-08-21',
    '2020-05-16',
    'Sophia pursued her undergraduate studies in Computer Science, gaining a solid foundation in programming, algorithms, data structures, and software development. She actively participated in various coding competitions, clubs, and workshops, further refining her technical skills and fostering a passion for innovation.',
    '1;2;3;4;5'
  ),
  (
    7,
    'Isabella',
    'Martinez',
    'isabella-martinez.png',
    '#ef5f9e',
    'abstract-lines-pattern_trans.png',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ),
  (
    8,
    'System',
    'Administrator',
    null,
    null,
    'abstract-lines-pattern_trans.png',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  );