CREATE TABLE UserData_t (
  UserID INT(9) NOT NULL Auto_Increment,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  ProfilePicture VARCHAR(255),
  ProfilePictureBorder VARCHAR(255) NOT NULL,
  ProfilePictureBackground VARCHAR(255) NOT NULL,
  MentorStatus BOOL NOT NULL,
  Rating INT(1),
  LocationCity VARCHAR(255),
  LocationState VARCHAR(255),
  Facebook VARCHAR(255),
  Twitter VARCHAR(255),
  Instagram VARCHAR(255),
  LinkedIn VARCHAR(255),
  Mentoring LONGTEXT,
  AboutMe LONGTEXT,
  WorkLocation VARCHAR(255),
  WorkStartDate DATE,
  WorkEndDate DATE,
  WorkDescription LONGTEXT,
  EducationLocation VARCHAR(255),
  EducationStartDate DATE,
  EducationEndDate DATE,
  EducationDescription LONGTEXT,
  Skills VARCHAR(255),
  Associations VARCHAR(255),
  CONSTRAINT UserData_PK PRIMARY KEY (UserID)
) Auto_Increment = 1;